### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by klapvogn** [cross-seed/cross-seed#278]
I have gotten this error a lot lately though I have made a config error in the conf. so I made a new one. But the error was back 

`(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 21)

(node:1) UnhandledPromiseRejectionWarning: SqliteError: select `last_run` from `job_log` where `name` = 'search' limit 1 - database is locked

    at Statement.all (<anonymous>)

    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)

    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)

    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)

    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)

    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)

    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async Timeout.loop [as _onTimeout] (file:///usr/src/app/dist/jobs.js:43:36)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)

(node:1) UnhandledPromiseRejectionWarning: SqliteError: select `last_run` from `job_log` where `name` = 'search' limit 1 - database is locked

    at Statement.all (<anonymous>)

    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)

    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)

    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)

    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)

    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)

    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async Timeout.loop [as _onTimeout] (file:///usr/src/app/dist/jobs.js:43:36)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 27)

(node:1) UnhandledPromiseRejectionWarning: SqliteError: select `last_run` from `job_log` where `name` = 'search' limit 1 - database is locked

    at Statement.all (<anonymous>)

    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)

    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)

    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)

    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)

    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)

    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async Timeout.loop [as _onTimeout] (file:///usr/src/app/dist/jobs.js:43:36)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 30)

(node:1) UnhandledPromiseRejectionWarning: SqliteError: select `last_run` from `job_log` where `name` = 'search' limit 1 - database is locked

    at Statement.all (<anonymous>)

    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)

    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)

    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)

    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)

    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)

    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async Timeout.loop [as _onTimeout] (file:///usr/src/app/dist/jobs.js:43:36)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 33)

(node:1) UnhandledPromiseRejectionWarning: SqliteError: select `last_run` from `job_log` where `name` = 'search' limit 1 - database is locked

    at Statement.all (<anonymous>)

    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)

    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)

    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)

    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)

    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)

    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async Timeout.loop [as _onTimeout] (file:///usr/src/app/dist/jobs.js:43:36)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 36)

(node:1) UnhandledPromiseRejectionWarning: SqliteError: select `last_run` from `job_log` where `name` = 'search' limit 1 - database is locked

    at Statement.all (<anonymous>)

    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)

    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)

    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)

    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)

    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)

    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async Timeout.loop [as _onTimeout] (file:///usr/src/app/dist/jobs.js:43:36)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 39)

(node:1) UnhandledPromiseRejectionWarning: SqliteError: select `last_run` from `job_log` where `name` = 'search' limit 1 - database is locked

    at Statement.all (<anonymous>)

    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)

    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)

    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)

    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)

    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)

    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async Timeout.loop [as _onTimeout] (file:///usr/src/app/dist/jobs.js:43:36)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 42)

(node:1) UnhandledPromiseRejectionWarning: SqliteError: select `last_run` from `job_log` where `name` = 'search' limit 1 - database is locked

    at Statement.all (<anonymous>)

    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)

    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)

    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)

    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)

    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)

    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async Timeout.loop [as _onTimeout] (file:///usr/src/app/dist/jobs.js:43:36)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 45)

(node:1) UnhandledPromiseRejectionWarning: SqliteError: select `last_run` from `job_log` where `name` = 'search' limit 1 - database is locked

    at Statement.all (<anonymous>)

    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)

    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)

    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)

    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)

    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)

    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async Timeout.loop [as _onTimeout] (file:///usr/src/app/dist/jobs.js:43:36)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 48)`

**Comment by mmgoodnow** [comment]
Are you running multiple instances of cross-seed at the same time?

**Comment by mmgoodnow** [comment]
looks like that might be the culprit. Try killing that

**Comment by mmgoodnow** [comment]
can you try these steps?

first, stop the docker container. Then, `cd` into cross-seed's config dir. After that, here are some things to check:

- That you don't have a hung process sitting on the file (unix: `$ fuser cross-seed.db` should say nothing)
- There isn't a `cross-seed.db-journal` file in the directory with `cross-seed.db`; this would indicate a crashed session that hasn't been cleaned up properly.
- Ask the database shell to check itself: `$ sqlite3 cross-seed.db "pragma integrity_check;"`
- Backup the database `$ sqlite3 cross-seed.db ".backup cross-seed.db.bak"`
- See if the backup works `$ sqlite3 cross-seed.db.bak ".schema"`

**Comment by mmgoodnow** [comment]
Can you post your config (redacting relevant parts)? I'm somewhat out of ideas

**Comment by mmgoodnow** [comment]
is there anything else that's weird about your setup? network file shares, maybe?

**Comment by KyleSanderson** [comment]
Can't take lock to run migrations: update `knex_migrations_lock` set `is_locked` = 1 where `is_locked` = 0 - unable to open database file
11
If you are sure migrations are not running you can release the lock manually by running 'knex migrate:unlock'
10
/usr/src/cross-seed/node_modules/knex/lib/migrations/migrate/Migrator.js:342
9
      throw new LockError(err.message);
8
            ^
7
6
MigrationLocked: update `knex_migrations_lock` set `is_locked` = 1 where `is_locked` = 0 - unable to open database file
5
    at /usr/src/cross-seed/node_modules/knex/lib/migrations/migrate/Migrator.js:342:13
4
    at async Migrator._runBatch (/usr/src/cross-seed/node_modules/knex/lib/migrations/migrate/Migrator.js:358:7)
3
    at async Command.<anonymous> (file:///usr/src/cross-seed/dist/cmd.js:128:9)
2
    at async Command.parseAsync (/usr/src/cross-seed/node_modules/commander/lib/command.js:923:5)
1
    at async file:///usr/src/cross-seed/dist/cmd.js:182:1

**Comment by mmgoodnow** [comment]
this is tentatively fixed in #341 
- database acquireConnectionTimeout increased
- WAL mode enabled
