### ISSUE TITLE
UNIQUE constraint failed: torrent.file_path

### ISSUE THREAD

**Issue by KyleSanderson** [cross-seed/cross-seed#367]
```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 438)
(node:1) UnhandledPromiseRejectionWarning: SqliteError: insert into `torrent` (`file_path`, `info_hash`, `name`) values ('/session/BT_backup/008f307e3852e0a70c5b44303a19479e194c4aec.torrent', '008f307e3852e0a70c5b44303a19479e194c4aec', 'RedHat') - UNIQUE constraint failed: torrent.file_path
    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)
    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async indexNewTorrents (file:///usr/src/app/dist/torrent.js:93:13)
    at async search (file:///usr/src/app/dist/server.js:71:5)
```

**Comment by KyleSanderson** [comment]
nice - thank you
