### ISSUE TITLE
[logs] Improve wording on rejected injects due differences such as file size

### ISSUE THREAD

**Issue by Greatdane** [cross-seed/cross-seed#588]
As per https://github.com/cross-seed/cross-seed/issues/160#issuecomment-1913159720, creating a new issue for this.

The wording for the verbose logs when deciding a torrent is sometimes not indicative of the actual issue. For example;

```
2024-01-26 10:51:21 �[36mverbose�[39m: [decide] Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv - no match for TorrentLeech torrent Migration 2023 1080p WEB-DL DDP5 1 Atmos H 264-FLUX - it has a different file tree
2024-01-26 10:51:31 �[36mverbose�[39m: [decide] Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv - no match for HDBits torrent Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX - it has a different file tree
2024-01-26 10:51:39 �[36mverbose�[39m: [decide] Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv - no match for MoreThanTV torrent Migration.2023.1080p.WEB-DL.DDPA5.1.H.264-FLUX - it has a different file tree
2024-01-26 10:51:59 �[36mverbose�[39m: [decide] Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv - no match for Blutopia (API) torrent Migration 2023 1080p MA WEB-DL DD+ 5.1 Atmos H.264-FLUX - it has a different file tree
```

The log here just states, `no match` with the reason `it has a different file tree`.

When i checked the torrent files manually with `cross-seed diff`, the rejection was actually due to a different file size;

```
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  {
    files: [
      {
+       length: 5397418467,
-       length: 5397420091,
        name: 'Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv',
        path: 'Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv'
      }
    ],
+   length: 5397418467,
-   length: 5397420091,
    name: 'Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv'
  }
    at diff (file:///usr/src/cross-seed/dist/diff.js:6:9)
    at Command.diffCmd (file:///usr/src/cross-seed/dist/diff.js:21:5)
    at async Command.parseAsync (/usr/src/cross-seed/node_modules/commander/lib/command.js:923:5)
    at async file:///usr/src/cross-seed/dist/cmd.js:232:1 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [Object],
  expected: [Object],
  operator: 'deepStrictEqual'
}
```

Maybe the logs can use the information `cross-seed diff` to give a more accurate reasoning for rejections.

**Comment by zakkarry** [comment]
I've already merged a fix for this to the next version branch. It's currently not in a testing/beta state from my perspective, but it has been addressed.
